// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj2f9YBBXybeTrvGcx8dkoTVRak1AdUBU',
    appId: '1:490606715219:web:8ee6fb1e62ac6053cec1a6',
    messagingSenderId: '490606715219',
    projectId: 'clincydev',
    authDomain: 'clincydev.firebaseapp.com',
    storageBucket: 'clincydev.firebasestorage.app',
    measurementId: 'G-2Y8Y3PYW68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUOJzLAVytYce2UmY2ASa3MYyPzFCjCNo',
    appId: '1:490606715219:android:eeaa0552038b370acec1a6',
    messagingSenderId: '490606715219',
    projectId: 'clincydev',
    storageBucket: 'clincydev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkj1vix8bepvubPMdpca6GE-r9I_GJruw',
    appId: '1:490606715219:ios:409a8b3591bfbb92cec1a6',
    messagingSenderId: '490606715219',
    projectId: 'clincydev',
    storageBucket: 'clincydev.firebasestorage.app',
    iosBundleId: 'com.example.bclincy',
  );
}
